tap 'homebrew/cask'
tap 'homebrew/cask-versions'
tap 'heroku/brew'

brew 'git'
brew 'wget'
brew 'wifi-password'
brew 'yarn'
brew 'heroku'

cask 'brave-browser'
cask '1password'
cask 'visual-studio-code'
cask 'iterm2'
cask 'docker'
cask 'slack'
cask 'spotify'
cask 'little-snitch'
cask 'vlc'
cask 'notunes'
